version: '3.8'

services:
  steam-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - STEAM_DOWNLOAD_PATH=/data/downloads
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=7860
    volumes:
      - steam-downloads:/data/downloads
      - steam-cmd:/app/steamcmd
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  steam-downloads:
    driver: local
  steam-cmd:
    driver: local